apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: mia-ollama
  labels:
    app: ollama-rocm
spec:
  type: NodePort
  selector:
    app: ollama-rocm
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 31434
    name: api
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-headless
  namespace: mia-ollama
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ollama-rocm
  ports:
  - port: 11434
    targetPort: 11434
